### ISSUE TITLE
Bar-ui Player loads song/playlist only around 40% of the time, seeking some guidance

### ISSUE THREAD

**Issue by etmarch** [Wenape/meteor-soundmanager#2]
I'm looking for some help in properly implementing Sound Manager 2 in meteor, as I am definitely confused in terms of where to place code, how to incorporate the player into templates, and just how to interact with this package in general. I have little experience using/integrating audio players. 

I know that the package is loading sound manager properly, as I can see this output in my console: 
SoundManager V2.97a.20140901 (HTML5-only mode) + html5PollingInterval (50ms)
 SoundManager 2 HTML5 support: mp3 = true, mp4 = true, ogg = true, opus = true, wav = true
SoundManager 2: Ready. ✓

However, the player usually appears "dead" - no songs loaded, cant minimize/maximize the playlist, etc... I literally copied and pasted the code from the bar-ui demo here: https://github.com/scottschiller/SoundManager2/blob/master/demo/bar-ui/index.html. I placed the bar-ui.js file into the /client/lib/ folder, I wrapped the html of the example player in a template called "audioPlayer", and I also copied and pasted the contents of the "demo.js" file into the Template.audioPlayer.rendered callback, in a sad attempt to properly load the player. Basically I have no idea what Im doing. Also, I just started getting this in the console: 
"soundManager: Queueing onready handler". 

If you could provide any documentation for implementing Sound Manager 2 in the 'Meteor' way, so I can use template events and helpers to dynamically load mp3s (im using CollectionFS package to upload song files on the server/gridFs), I would be very grateful! Thanks for the great package too.

**Comment by Wenape** [comment]
In my case, there was not much interaction between Meteor and SoundManager apart from an event triggering play/pause on the current file. The SoundManager API provided me with all I needed

**Comment by Wenape** [comment]
In my case, there was not much interaction between Meteor and SoundManager apart from an event triggering play/pause on the current file. The SoundManager API provided me with all I needed.

This is my current approach and what you could use:


helpers.js

    soundManager.createSound({
        id: "A unique id here",
        url: "Path to the file uploaded using CollectionsFS",
        autoLoad: true,
        stream: true,
        onload: function () { ... }, // Show an indicator on the UI that the file is loaded
        whileplaying: function () { ... }, // Optional callback to update playback position (you could use a Session var to update an element of the UI re-actively)
        onfinish: function () { 
          // remember to release audio resources
          soundManager.unload("A unique id here");
          soundManager.destroySound("A unique id here");

          // maybe play next file from playlist?
        }
    });


Events

* play/pause

    soundManager.play("A unique id here");
    soundManager.pause("A unique id here");

* loading a file (after it get completely uploaded): have an event that triggers `soundManager.createSound`. Pass the `_id`of the file you want to load as an argument.

**Comment by etmarch** [comment]
Excellent, thank you for providing me with some sample code, this makes a lot more sense now. I'll mark this as closed.

**Comment by etmarch** [comment]
I have one further question to clarify things - Don't I need to call soundManager.createSound for each and every song I want to play? So I'm assuming that first createSound call in helpers.js is to set up the first song to be loaded, and after that call createSound in template files attached to certain events? I'm still new to meteor, I apologize if im asking really basic questions. Thanks again for your help.

**Comment by Wenape** [comment]
That's correct, you need to call `soundManager.createSound` function for every song you want to play. What you should ideally do is have a function you can call from events and callbacks:

helpers.js

    playSong = function (_id) {
      soundManager.createSound({
       ...
         other options from above,
         autoPlay: true, // play this song automatically instead of using soundManager.play(_id) to manually start it
         other options from above,
       ...
      });
    }

Template (lists all songs)

    <template name="playlist">
      {{#each song}}
        <div class="song">{{name}} - {{artist}}</div>
      {{/each}}
    </template>

Events

    Template.playlist.helpers({
       'click .song' : function (event, template) {
         var _id = template.data._id;
         playSong(_id);
       }
    });

**Comment by etmarch** [comment]
Ah okay, that makes sense, thanks. And for the artist and name, I'll just pull that data from that songs Collection Fs file metadata object?

**Comment by Wenape** [comment]
Yes, you can grab the metadata from the documents inside your collection (depending how you structured it). 

Also, remember that the template above is just an example. You should structure it as you see fit (maybe you could include duration of the song and/or it's artwork).

**Comment by etmarch** [comment]
Yeah, I plan on getting the artist of the song as well. I guess my last question is what do you recommend in terms of implementing the "time bar", or whatever its called to show how far into a song you are? I'm thinking use setInterval to create a repeating function which which grabs and returns the  'position' property of the current sound object? 

Then to display it, something like (currentPosition * 100 / totalDuration)% in a canvas element might work to start. Appreciate all the advice.

**Comment by Wenape** [comment]
No need to create a setInterval function. You can use the following callback which runs repeatedly as the song is playing:

    soundManager.createSound({
      ...
      whileplaying: function () { 
        // update song progress
        Session.set('progress', this.position * 100 / this.duration);
      },
      ...
    });

Helper

    Template.playlist.helpers({
      getProgress: function () {
        return Session.get('progress');
      }
    });

Template

    <div class="progress-bar" style="background: green; width: {{getProgress}}"> 
    </div>

**Comment by etmarch** [comment]
Great, very convenient!

**Comment by etmarch** [comment]
Sorry to both you again Wenape, but I'm actually having some serious trouble at the moment getting Soundmanager2 to work at all. I think I'm confused what steps I need to take from the beginning to ensure that everything is loaded properly. I am experiencing the strangest functionality - sometimes on page load the player is able to load the first song, and I am able to use it normally (all buttons on the player work, I can see the playlist, etc..). Other times, the player wont display a song title on page load, and clicking any of the buttons on the player doesnt do anything. There are no warnings or errors, its just doesnt do anything when clicked. 

So if we could rewind a bit - do I need to call soundManager.setup(), or was that done already in your package? Because I have no idea what the url to the .swf file is. If I need to call it myself, should i just do it right in my /client/client.js file? 

The strange thing is that the song playlist is hardcoded into the template html file, so I have no idea why sometimes it loads songs on page load, and other times it doesnt: 
```     <ul class="sm2-playlist-bd">
                        <li><a href="http://freshly-ground.com/data/audio/sm2/The%20Fugitives%20-%20Graffiti%20Sex.mp3"><b>SonReal</b> - LA<span class="label">Explicit</span></a>
                        </li>
                        <li><a href="/music/song2.mp3"><b>Song 2</b>
                            - People Asking <span class="label">Explicit</span></a>
                        </li>
                        <li>
                            <a href="/music/song3.mp3"><b>SonReal</b>
                                - Already There Remix ft. Rich Kidd, Saukrates <span class="label">Explicit</span></a>
                        </li>
                        <li><a href="http://freshly-ground.com/data/audio/sm2/The%20Fugitives%20-%20Graffiti%20Sex.mp3"><b>The
                             Fugitives</b> - Graffiti Sex</a>
                         </li>
                         <li>
                             <a href="http://freshly-ground.com/data/audio/sm2/Adrian%20Glynn%20-%20Seven%20Or%20Eight%20Days.mp3"><b>Adrian
                                 Glynn</b> - Seven Or Eight Days</a>
                         </li>
                         <li>
                             <a href="http://freshly-ground.com/data/audio/sm2/SonReal%20-%20I%20Tried.mp3"><b>SonReal</b>
                                 - I Tried</a>
                         </li>
                    </ul> ```

Also, it never loads for Firefox ever, but Chrome and Safari have a higher percentage of being "usable". I know I've already asked for a lot, but if you could help me figure out why my player wont work, I would be very appreciative. Here is a link to my project: https://github.com/etmarch/trackplayer-dev.

**Comment by Wenape** [comment]
At this point, most of your errors are probably project specific. If you include more functionality, you need to take more things into consideration, all of which probably have to do with more than soundManager itself.

The soundManager plugin is loaded simultaneously with other packages. This is before any templates are loaded and rendered. soundManager should be ready to work before any DOM is laid out. For everything you do, you need to know the order in which Meteor loads files and dependencies.

I'm not calling `soundManager.setup()` anywhere on my project. This is because I don't need to setup any extra parameters apart from the default. If you do, you need to be careful where you call it.

Now, the most complicated thing I have found about using soundManager are the different bugs you stumble upon. Most of the times these bugs don't even have to do which soundManager itself. Remember, you are dealing a bunch of different file extensions, different browsers which users can use and multiple dependencies from Meteor that could clash with any soundManager functionality you use (like bar-ui player).

For example, soundManager stopped working for me about a month ago only on Firefox (and just for a specific extension: .mp4). Did I change something on my project which caused the error? Did soundManager have a bug? or I'm just unlucky. The problem was that I had updated Firefox just a week ago and for some reason this new version with soundManager and .mp4 files specifically. But, of course soundManager didn't mention this was an error with Firefox so I thought it was a bug with soundManager. Finally, I found out what it was by exploring the issue tracker of soundManager.

Also, I'm not using the bar-ui player and I still had my complications. So, try learning more about Meteor, specially if you are dealing which a lot of templates which interact with soundManager. Also, be sure to check the soundManager issue tracker for any bug that could be affecting your project.

**Comment by etmarch** [comment]
Thank you for such a detailed explanation! So first things first, I should definitely start with getting the most basic functionality of soundManager to work with my project, and only after that, see if I can scale up to something like the bar-ui. Basically, I need to stop assuming that this is some easy drop-in functionality, and get my hands dirty with trying out different combinations and debugging. 

I already scour the soundManager2 forums, so I will continue to do that as well. One thing that I am still confused about though (this is pretty unrelated to your package, don't feel obliged to answer), is the ordering of the packages that are loaded - can adding packages in a different order actually affect the way my Meteor app operates? If so, thats a pretty scary thought, as I have basically been adding any and all packages I come across that appear to be even remotely useful, many I have not even used yet, and in absolutely no order. A thorough review of Meteor basics is in my near future, thank you very much for taking the time to help a rookie like me. 

PS - Do any of your projects have a donate button? I'd like to give back in whatever way I can.

**Comment by Wenape** [comment]
Each package defines any other files/packages it uses as dependencies inside a [config file](http://docs.meteor.com/#/full/packagedefinition). The packages are loaded taking in account their dependency hierarchy. So you shouldn't worry about any problems between packages.

But, If you add any javascript library not as a package, but instead inside a folder in your project, you could have a problem (not usually though). That's why any library you need is usually wrapped inside a Meteor package. As is the case with this package.

About a donate button, all my packages are quite simple, they do not require much maintenance so it didn't occur to me to put a donate button.

**Comment by etmarch** [comment]
I tried basically everything I could think of to try and get the bar-ui demo code to work, but after several hours I realized its fruitless. Instead, I have used your code as a base to set up my own custom player, and so far its working quite well (on all browsers, hurray!). One change in particular I made to your sample code: 
A) Wrapping the first soundManager.createSound() in a soundManager.setup onready call due to some loading issues I was seeing.   

Im feeling pretty comfortable building a basic player at this point, so thank you again. My very last question: is it feasible to set up soundManager to play all songs in one specific player/template? I don't see why it wouldn't be, because as far as im concerned I can make all soundManager actions (play, pause, etc..) global template helpers. Is it possible for an event/action that occured in one template to update the context/data of a seperate unrelated template? For instance, I click a song on the homepage, which calls a global helper function that assigns that song's data to the main player.

Thanks much for your help as always!

**Comment by Wenape** [comment]
Sure it's possible. You could use a Session variable to store the data of the song you want to play. This Session variable would serve as the data context for the player's current song. Any event from a template could change this variable which in turn would update the data context of the player re-actively.

You can define a tracker as well to stop the last song and play the new one:

    Tracker.autorun(function () {
	if (Session.get('playSong')) {

	  // stop or destroy the last song (whatever you want to do)
  	  soundManager.stop(lastSong._id);

  	  // play the song just added
  	  playSong(Session.get('playSong')._id);
	};
    });

**Comment by etmarch** [comment]
Ah, of course, Session variables are perfect in this instance - I really should have been able to deduce that on my own. Thanks again for all of your help.

**Comment by etmarch** [comment]
Hello again, friend. So, since we left off, I have been able to construct a pretty serious audio player that contains the same standard functionality you would expect. Users upload files from the app into a couple S3 buckets using the cfs-s3 package, and now that I have deployed my app on Digital Ocean with an oplong-enabled Mongo DB from compose.io, everything is working very smoothly - really fast so far - but only in Chrome and FireFox. 

Safari on the other hand, consistently stalls when loading the mp3 files, and sometimes does not even play them at all. Someone who tested my site using Safari reported back that it took 4 minutes (!) after creating the sound for the song to play. This is only for Safari, as Chrome and FireFox are blazing fast. Here is some additional info: Safari is able to load and play mp3 files stored in the filesystem decently, but as soon as an S3 url is clicked, the debugging reports that the current song never makes it past the "buffer state change: 1", and soon after the debug log outputs "stalled". 

I've been trying many different options (autoload, streaming, etc..) but so far to no avail. Do you happen to know why Safari takes so damn long to buffer and load a song? Is this issue even really related to SoundManager, or is this most likely an S3 thing, seeing as how Safari can still play files in the local filesystem decently well? I figured I would float this issue by you since you have been so knowledgable in the past, and I am really at my wits end with this stupid browser. Thanks as usual, and if I stumble upon the reason myself, I will let you know.

**Comment by Wenape** [comment]
I've never experienced any special problems with Safari. It plays files as fast as Chrome or Firefox for me. The files being either local files or from an external source. Maybe it's an issue from the S3 buckets. It could be an issue with the config of the policy or something.

**Comment by etmarch** [comment]
Okay, thanks anyways. Would you have any idea how I could possible modify the HTTP response header to customize the byte-serving behavior? relevant link: http://www.schillmania.com/projects/soundmanager2/doc/technotes/#byte-serving

**Comment by Wenape** [comment]
Maybe this could help you: http://stackoverflow.com/questions/8993681/soundmanager-w-html5-audio-is-causing-206-partial-content-errors

**Comment by etmarch** [comment]
Thanks for the article.
