### ISSUE TITLE
Please update SM2 to latest version

### ISSUE THREAD

**Issue by bkuri** [Wenape/meteor-soundmanager#3]
Thanks for providing a meteor package. I would appreciate a library update if it's not too much trouble.

FYI, the latest version is V2.97a.20150601

Release Notes:
http://www.schillmania.com/projects/soundmanager2/doc/download/#revision-history

Download link:
http://www.schillmania.com/projects/soundmanager2/download/soundmanagerv297a-20150601.zip

Thanks again!

**Comment by Wenape** [comment]
I'ts done. I included the version you specified, the package should be lighter now as it included the  un-minified version before.

**Comment by bkuri** [comment]
That's a nice bonus! :+1:

I tried updating using `meteor update`, but it seems the version number is the same. I'll try cloning it through git and report back.

**Comment by Wenape** [comment]
You're right, I forgot to bump the version number before publishing on atmosphere. Now it should be working.

**Comment by bkuri** [comment]
Yes, that did the trick. Many thanks!
