### ISSUE TITLE
Hide old/renamed Atmosphere packages

### ISSUE THREAD

**Issue by dandv** [Wenape/meteor-soundmanager#4]
Hi @Wenape,

Thanks for marking [several](https://atmospherejs.com/wenape/meteor-soundmanager) of your Atmosphere [packages](https://atmospherejs.com/wenape/fview-infinitescroll) as no longer working. You can also hide them from Atmosphere searches by running

    meteor admin set-unmigrated <package-name>

Thanks!

**Comment by Wenape** [comment]
Done. It's nice this feature was added.
